version: '3.1'

services:

# docker network create frontier-network
  
  frontier:
    image: crawlercommons/url-frontier:1.2
    container_name: frontier
    ports:
      - 127.0.0.1:7071:7071
    command: -s 9100
    logging:
      driver: loki
      options:
        loki-url: "https://loki:3100/loki/api/v1/push"

  prometheus:
    image: prom/prometheus 
    container_name: prometheus
    ports:
      - 127.0.0.1:9090:9090
    volumes:
      -  $PWD:/etc/prometheus
    command: --web.enable-lifecycle  --config.file=/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana
    container_name: grafana
    volumes:
      - $PWD/provisioning:/etc/grafana/provisioning/
    ports:
      - "127.0.0.1:3000:3000" 

  loki:
    image: grafana/loki:2.4.2
    container_name: loki
    ports:
      - "127.0.0.1:3100:3100"
    volumes:
      - $PWD:/mnt/config
    command: --config.file=/mnt/config/loki-config.yaml

networks:
  default:
    external: true
    name: frontier-network
