version: '3.1'

services:
 
  frontier:
    image: crawlercommons/url-frontier:2.0
    container_name: frontier
    ports:
      - 127.0.0.1:7071:7071
    command: -s 9100
    logging:
      driver: loki
      options:
        loki-url: "http://localhost:3100/loki/api/v1/push"
    networks:
      - frontier

  prometheus:
    image: prom/prometheus 
    container_name: prometheus
    ports:
      - 127.0.0.1:9090:9090
    volumes:
      -  $PWD:/etc/prometheus
    command: --web.enable-lifecycle  --config.file=/etc/prometheus/prometheus.yml
    networks:
      - frontier

  grafana:
    image: grafana/grafana:8.3.5
    container_name: grafana
    volumes:
      - $PWD/provisioning:/etc/grafana/provisioning/
    ports:
      - "127.0.0.1:3000:3000"
    networks:
      - frontier

  loki:
    image: grafana/loki:2.4.2
    container_name: loki
    ports:
      - "127.0.0.1:3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - frontier

networks:
  frontier:
