name: Dockerhub Deployment

on:
  push

jobs:
  deploy:
    name: Docker image deployment
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Extract version
        run: echo "::set-output name=VERSION::$(cat pom.xml | grep '<version>.*</version>$' | grep -m1 '' | awk -F'[><]' '{print $3}')"
        id: version

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          platforms: linux/amd64
          tags: |
            crawlercommons/url-frontier:latest
            crawlercommons/url-frontier:${{ steps.version.outputs.VERSION }}
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
